; PlatformIO Project Configuration
; iCar BLE Bridge for BYD Dolphin Mini
;
; Upload: pio run -t upload
; Monitor: pio device monitor

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags = -DCORE_DEBUG_LEVEL=1
