; PlatformIO Project Configuration
; iCar BLE Bridge for BYD Dolphin Mini
;
; Upload: pio run -t upload
; Monitor: pio device monitor

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
build_flags = -DCORE_DEBUG_LEVEL=3
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
